subclass_name: AGN_NumberDensities.AGN_NumberDensity
band: i
rest_frame_band: i
Mag_lim: -22.5
z_lim: [0.3, 2.2]
observation: 'SDSS'
validation_range: [16., 19.5]
included_by_default: true
description: 'Plot N and N(<mag) distributions for selected magnitude bound and redshift range in specified band and compare with SDSS data from Richards 2006'
