subclass_name: DeltaSigma.DeltaSigma

data: 'cfhtlens'
zmin_l: 0.2
zmax_l: 0.4
zmin_s: 0.41
zmax_s: 1.0
max_background_galaxies: 100000
zmax: 3.0
Rmin: 0.05
Rmax: 15.0
nR: 20

description: 'Plot Delta Sigma for CFHTLenS sample.'

data_filename: 'delta_sigma/cfhtlens_DS.dat'


