subclass_name: EmlineRatioTest.EmlineRatioTest
emline_ratio1: 'oii/oiii'
emline_ratio2: 'hb/oiii'
sdss_file: 'descqa/data/sdss_emission_lines/sdss_query_snr10_ew.csv'
sdss_drawnum: 30000
sim_drawnum: 30000
loz_lo: 0.0
loz_hi: 0.4
hiz_lo: 0.4
hiz_hi: 0.7
loz_band: 'r'
hiz_band: 'i'
truncate_cat_name: True
description: 'Plots ratios of emission line luminosities from SDSS data and DESC simulations and compares the two 2-D distributions.'