subclass_name: NumberDensityVersusRedshift.NumberDensityVersusRedshift
band: r
zlo: 0.
zhi: 1.0
Nbins: 40
observation: 'DEEP2_JAN'
included_by_default: true
description: 'Plot N(z) distributions for selected magnitude cuts in specified band and compare with fits to DEEP2 data from J. A. Newman (priv. comm.)'
